### PR TITLE
Issue #264: `__mklexer__` was not setting data.

### PR DESCRIPTION
**Pull request by ysiraichi**
Setting `lex.input` data at `__mklexer__` instead of `push`.

### CODE REVIEW

**Comment by 1ucian0** [comment]
I think this fix needs some explanation. I would help if you can extend the tests with the example from the #264. Also, depending on the impact in the rest of the code base, it would make sense to rename `print_tokens` to `get_tokens`. What do you think?

**Comment by ysiraichi** [comment]
Oh, sorry. The thing was that the input data was not being set when passing the filename through the constructor (which I think was the desired behaviour). That was the reason why it was not printing anything.

I also agree that it is probably better to return the tokens. I was thinking on an array of tokens. What do you think?

**Comment by 1ucian0** [comment]
maybe a generator? The amount of tokens for very large QASM files might be huge and I can think in applications that just need to search for the existence of a particular one.

**Comment by ysiraichi** [comment]
What about the tests?
Should I create one test for every kind token?

**Comment by 1ucian0** [comment]
I think something along the following lines in `test_qasm_parser.py` will suffices.  
```
for i in qasm.Qasm(filename='example.qasm').get_tokens(): # you can find qasm files in test/python/qasm/
    self.assertTrue(isinstance(i,ply.lex.LexToken))
```
Remember to update the docstring of `get_token`, mentioning that now is a generator. After this, I think we are all set! This will fix #264

**Comment by 1ucian0** [comment]
Thanks @ysiraichi for the contribution!

**Pull request merged**
