### PR TITLE
Mapper issue 159

### PR DESCRIPTION
**Pull request by awcross1**
Change behavior of the single qubit gate optimization to remove u1(2*pi) gates.

## Description
This change addresses issue #159 and corrects minor issues with some single qubit gate simplifications not occurring due to the transition to symbolic math.

## Motivation and Context
This fixes issue #159 and a related issue discovered in the course of fixing the original issue.

## How Has This Been Tested?
This has been tested against the example submitted in the issue and one other example. A new test was added and the existing tests were updated. All tests pass.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by awcross1** [comment]
One of the tests fails in Python 3.5 but not in 3.6. The output is correct but differs from what is expected. Perhaps there is an issue with the seed.

**Comment by awcross1** [comment]
I need to add a few new tests.

**Comment by diego-plan9** [comment]
> I need to add a few new tests.

It's looking good so far! As a matter of fact, I did not mark it as approved as I understand the intention is to add those new tests before marking the PR as completed? It would be extremely nice to have them, specially as this PR exercises some functionality that is not so well covered by our current test suite.

I have also:
* moved the test from #172 (and #173) to this PR, at 00aabc0; as it is closely related and makes it more handy for testing it along the changes.
* modified the failing `test_math_domain_error`, in order to expect different results depending on the Python version. This is a workaround in order to not block this PR, and the real issue (which indeed seems to be a problem with how the seed/the randomness is handled) should be address in a new PR - I'll make a note.

**Comment by adjs** [comment]
Unnecessary calls to sympy.N can increase computational cost. I have removed all calls from N to constant values. https://github.com/awcross1/qiskit-sdk-py/pull/1

**Comment by diego-plan9** [comment]
I have just rebased the PR against the current `master`, as it seems some previous merging were not clean and it was showing some commits incorrectly, and also tweaked a bit the style of the tests in the last commit. There is still the issue of `test_optimize_1q_gates_issue159` failing for Python 3.5, but otherwise is looking good!

**Comment by diego-plan9** [comment]
Self-reminder to comment on https://github.com/QISKit/qiskit-tutorial/issues/65 once this PR is merged.

**Comment by awcross1** [comment]
Thanks @diego-plan9 that is better. I don't have any more changes except to fix the Python 3.5 test.

**Pull request merged**
