### PR TITLE
Adding a Chinese translation of README

### PR DESCRIPTION
**Pull request by LuhangYang**
## Description
Adding a Chinese translation of README.md

## Checklist:

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by diego-plan9** [comment]
Thanks, @LuhangYang ! Two small requests:

* can you add a line to the ``## Multilanguage guide`` in the root `README.md`, in a similar way that currently the line for the Korean translation is linked?ie.
```

**Comment by LuhangYang** [comment]
Thanks @diego-plan9 !   Yes, I have revised them.

**Comment by liupibm** [comment]
Thanks @LuhangYang 
Two small requests:
1 附属文件 => 依赖文件
PIP 会自动处理所有的附属文件，并替您将它们更新到最新的（经过测试的）软件版本。 PIP 为以下平台预装有二进制版本

2 some links are broken, e.g., 
可以在 **这里**找到此例的脚本。
在IBM Q experience网页上取得一个API 令牌： "My Account" > "Personal Access Token"。这个API令牌将使您可以在IBM Q 体验后端上运行您的程序。 **示例**

**Comment by LuhangYang** [comment]
Thanks @liupibm ! Problems fixed.

**Pull request merged**
