### PR TITLE
Resolves #262: add qiskit.backend methods...

### LINKED ISSUE #262: add qiskit.backend methods for getting parameter and calibration data
Add methods to qiskit.backends for getting parameters and calibration data.

## Current Behavior
Currently the way to obtain backend parameters and calibration is through QuantumProgram methods. These could be moved to qiskit.backends.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 3.6.1):
* Operating System and version:

### PR DESCRIPTION
**Pull request by ewinston**
Adds backend methods for getting parameter, calibration, and status similar to how calibration is currently retrieved.

## Description

One difference between how this is implemented and configuration, however, is that these methods get query the device whenever the method is called whereas "configuration" only gets it when backends are discovered.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by ajavadia** [comment]
@ewinston Thanks Erick. Getting `status`, `configuration`, `calibration` and `parameters` are indeed best done using the `backends` module.

I made some linter changes, and marked as approved. 

@jaygambetta is creating some extra features such as DeprecationWarnings, to warn users that support for these functions will be dropped from the `quantumprogram` module.

**Comment by jaygambetta** [comment]
@ajavadia @ewinston there was some test i missed that are using the old coupling map. I will try and fix them but we should start to move towards the new coupling_map otherwise it grow too much to change when the api changes this is why i put into backend.configuations that hack :-)

**Comment by diego-plan9** [comment]
Yes, they have a different semantic meaning (and also are treated differently): the short version is that `logger.warning` (and the rest of `logger.xxx()` methods) should still be the preferred method for "printing notable events and information for the end user", while warnings are more for "notifying the user that he needs to take action and modify his code" (https://docs.python.org/3/howto/logging.html#when-to-use-logging). In practice it is usually way less common to have the need `warnings`, but if you feel it's needed we can add some mention of it in our documentation?

**Comment by jaygambetta** [comment]
@ajavadia @ewinston @diego-plan9 i think we are good.

**Comment by diego-plan9** [comment]
It seems we are indeed! I did some further plumbing at 864a068 (mostly, revising some lines that were commented probably inadvertently and homogenized a bit the family of `qiskit.backend` functions that retrieve information) - merging, thanks everyone!

**Pull request merged**
