### PR TITLE
renaming schemas

### PR DESCRIPTION
**Pull request by jaygambetta**
I would like to use full names

Schemas are still not used so no need to test.

### CODE REVIEW

**Comment by dcmckayibm** [comment]
I'm not sure you added the renamed ones

**Comment by ajavadia** [comment]
for consistency, can we have all the examples be like `XXX_example.json` and all the schemas like `YYY_schema.json`.

Right now the schemas are ok, but the examples are a bit disorganized in name.

**Comment by jaygambetta** [comment]
@ajavadia just for you but what did i start :-)

**Comment by dcmckayibm** [comment]
Should we change `available` to `operational` in `backend_status_schema.json`?

**Comment by jaygambetta** [comment]
Thanks Ali

**Pull request merged**
