### PR TITLE
Extend Coupling class to allow for generation, saving and plotting of layouts/coupling maps

### PR DESCRIPTION
**Pull request by afu1**
When importing `qiskit.tools.layouts` the `Coupling` class in `qiskit.mapper._coupling` is extended to include the following methods and data structures:
- Adds the methods gen_map, get_dict, plot, fexport and fimport.
- Adds the data structures pos, name, description.

## Description
`import qiskit.tools.layouts` adds the methods:

  get_dict : returns a dictionary representation of the coupling map
         plot : plots the coupling map 
   fexport : saves the coupling map to a json file
   fimport : loads the coupling map from a json file
gen_map : generates a standard coupling map layout

The following standard layouts are available as of now with the corresponding parameters:
``` 
 "linear"  : n, order
 "circle"  : n, order
 "rect"    : n_right, n_down, order, defects
 "torus"   : n_right, n_down, order, defects
 "ibmqx2"  : -
 "ibmqx3"  : -
 "ibmqx4"  : -
 "ibmqx5"  : -
 "ibmq1"   : -
 
           n  : number of qubits in coupling map
      n_right : number of qubits horizontally 
       n_down : number of qubits vertically
        order : orientation of the coupling (float between 0.0  and 1.0).
                For a value of 0.0 the qubits are coupled from right to left.
                For a value of 1.0 the qubits are coupled from left to right.
                For values 0.0 < order < 1.0 random couplings are chosen with
                probability of left-to-right given by 'order'.
      defects : number of defects to introduce in the lattice.
                A negative number of 'defects' will attempt to remove as many random links (< = abs(defects))
                as possible without isolating any qubit from the lattice.
                A positive number of 'defects' will add links to the lattice randmomly until either
                all-to-all connectivity is reached or the number of added links reaches 'defects'
```

For creating an automatic layout the code makes use of `pygraphviz` if it is available and uses `networkx` otherwise. The latter does not work well for creating automatic layouts.

## Motivation and Context
The proposed additions add generation, layouting and plotting of coupling maps to qiskit. The changes could also be added directly to the definition of Coupling in `qiskit.mapper._coupling`. Adding them first to `qiskit.tools` would allow us to test things first. The Jupyter notebook  `generate_and_plot_coupling_maps.ipynb` in examples shows how the additions work. This notebook could also move to `qiskit-tutorials`.

## How Has This Been Tested?
I have run all routines and tested the outcome using qiskit v0.4.8.
The changes should not affect the use of the Coupling class in any other context. After extending the class definition it can still be used in the original way.

## Screenshots (if appropriate):
Example :
image

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by ajavadia** [comment]
Thanks for submitting this PR @afu1! It will be a really nice tool addition. I will try to review the code in detail, but for now here are some high level comments:

1- We removed all jupyter notebooks from the SDK, in favor of gathering them in the tutorials. Your notebook can be included as a visualization tutorial; can you please make a separate PR there?

2- Could you add a few tests in `test/python/`? We are making a concerted effort to increase test coverage of the code in some of the recent issues. This could be 

3- I wonder if we should use a name other than "layout", since in the current SDK code layout is already used to mean something else (i.e. in the mapper stage, layout is a dictionary of program qubits to on-chip qubits. It is also a flag to compile/execute). How about "topology" or "geometry"?

**Comment by rraymondhp** [comment]
@afu1  The same with @ajavadia , I think this will be a good tutorial for demonstrating QISKit functionalities. Would you mind writing a jupyter notebook for this?

**Comment by afu1** [comment]
Ali and Rudy,
thanks for your input.
I was aware of some of the issues you raise but wanted to discuss:
- naming: the extensions generates coupling maps and lays them out spatially. So topology is not a good name. How about `qiskit.tools.cpl_maps` or `qiskit.tools.coupling_maps` or `qiskit.tools.coupling_layouts` or `qiskit.tools.coupling_extensions`?
- tests: I did not think enough about this and therefore thought that it's hard to test a plotting extensions but I can add a comparison between an instance generated with the __init__ functionality and one generated by hand. Any suggestions what else to test? 
- import of `pygraphviz`: should this be added to requirements or do you want to keep it flexible and use it only when already installed? It is much better in laying out graphs than networkx. I can add it to the requirements if you agree.
- Since this is at the moment a temporary extension I was not sure how to include the jupyter notebook tutorial. Do you agree that I put it in the `1_introduction` subfolder and that we add a line in the index.ipynb under this topic?

**Comment by rraymondhp** [comment]
@afu1  Thanks for the quick response. I can manage adding link from the index page. At the moment, it suffices if you can write the notebook showing how to generate `layout` and print them. 
As you pointed out, because the stable branch of qiskit-sdk-py does not support it yet, we will use the tutorial with the master/up-to-date branch.

**Comment by afu1** [comment]
@rraymondhp You may have seen from Alis comments above that the jupyter tutorial notebook was already part of this PR. I will update it when the name for the extension is fixed and make a PR to the tutorials.

**Comment by ajavadia** [comment]
* I think `coupling_layouts` is a good name.

* Including the tutorial in `1_introduction` sounds good. 

* Ideally the tests should test the functionality of every function with an `assert`, to make sure they perform as expected. For example, you would write a separate test for each layout (linear, torus, circle, ibmqx2, etc.) and test some property, like `pos`. All of these would go in a file named `test_coupling_layouts.py`. 
For example, I think the backend names might change soon (no longer ibmqx). If there are no tests that touch that part of your code, we might not realize that the coupling_layouts need to be updated as well.

* Could you also address the [code style issues](https://travis-ci.org/QISKit/qiskit-sdk-py/jobs/345803220) that are causing the linter checks to fail?

* Regarding `pygraphviz` as requirement, I'm going to ask @diego-plan9 to pitch in. Generally it is good to keep dependencies light, but it may also depend on how much better pygraphviz is over networkx. Do the pictures below accurately depict the difference between networkx and pygraphviz outputs?
- **pygraphviz**
image

- **networkx**
image

**Comment by afu1** [comment]
@ajavadia what version of networkx are you using? There should be no difference between these two plots. I'm using v2.1 which uses arrows and I think we should switch to that version sometime soon (at the moment v1.11 is still allowed but the mapper code could be improved with v 2.1).

I tried to make a difference between just the coupling map (which to me is more the topology of the coupling graph) and the layout of the qubits which I tried to refer to for the placement of the qubits on a 2D plane. I probably mixed these two from time to time. Anyway, the plotter will not know how to plot the qubits if only the coupling graph (coupling map) is given. There are may ways to do that. So the plot routine first checks if there are entries in the .pos data structure of the Coupling instance. If there is it uses these positions to plot the map. If not it checks if pygraphviz is present and if so creates qubit positions in the .pos structure for the current Coupling instance. If pygraphviz is not present networkx is used to layout the qubits in space. While pygraphviz does a pretty good job for the 17 qubit chip:
image
networkx does not:
image

The other points I'll address. Thanks for your input!

**Comment by ajavadia** [comment]
@afu1 I have networkx v1.11, which seems compatible with what is specified in `requirements.txt`. 
This was discussed in #259 and #261, but in the end the networkx dependency was not bumped up to 2.0. Will something break if we require networkx 2.0 or higher? (@diego-plan9 or @atilag may have some thoughts here).

**Comment by 1ucian0** [comment]
Small note about `networkx==2.0`, in PR #313 all the tests are passing with 2.0  (CC @ajavadia @diego-plan9 @atilag)

**Comment by diego-plan9** [comment]
Thanks for the neat contribution, @afu1 ! In regards to the hot topics:

* **dropping support for `networkx` 1.x:** I'm actually relying the decision onto you, due to being the one that suggested dropping support eventually during #259! I believe the main hurdle (anaconda not including `network==2.x`) is not an issue anymore, and in principle, requiring recent-but-not-bleeding-edge versions is a good practice. However, ideally the dropping of 1.x should include the refactoring for using 2.x functions throughout the code - probably as part of a new PR (or jumping in Luciano's #313 ).

* **tests**: as @ajavadia suggested, we encourage having some tests, as otherwise maintainability suffers too much. I'd suggest at least:
  * having one test that exercises the full functionality (ie. something similar to the current `Coupling.plot()`). Instead of comparing to a manually-generated file (as the actual binary contents will probably change depending on versions and os specifics), it should be safe to just have a general assertion making sure the tests reaches the end successfully, as that is the goal of that test - much in the spirit of [some existing tests](https://github.com/QISKit/qiskit-sdk-py/blob/master/test/python/test_visualization.py#L138).
  * having several tests that exercise functionality individually, for example the ones Ali suggested.

* **pygraphviz dependency**: in this case, I think it is more sensible to make it optional. As Ali mentioned, we need to balance the need for keeping the dependencies light (in this case it is light, but it requires a `libcgraph-dev` or similar package for compiling during installation), the centrality of the feature in regards to the SDK, and make some tradeoffs. Can you:
  * add some code [for checking that the package is installed](https://github.com/QISKit/qiskit-sdk-py/blob/master/qiskit/tools/visualization.py#L39) and [failing gracefully if not](https://github.com/QISKit/qiskit-sdk-py/blob/master/qiskit/tools/visualization.py#L737)?
  * add a note in the docstring of the main function to note that it requires `pygraphviz`
  * add an entry to the `extras_require` in [setup.py.in](https://github.com/QISKit/qiskit-sdk-py/blob/master/setup.py.in#L146)

I also have some concerns about modifying `Coupling` dynamically, which will address in an upcoming comment.

**Comment by diego-plan9** [comment]
In regards to adding methods and attributes to `Coupling` dynamically: while it has its uses and I believe I understand the rationale of trying to "extend" the original class while keeping a minimal impact on it, it's a mechanism that has some strong drawbacks:
* arguably the most important is the penalty to discoverability: if the methods and attributes are added at runtime, it prevents static analysis. Tools, checkers, and more importantly developers cannot know what members are available for `Coupling` directly via the usual inspection methods, which hinders maintainability.
* derived from the above, the chance of unwanted side effects increases, due to the new `self.xxx` attributes and methods that can be inadvertently reused by other features that might rely on the original definition of the class.
* also derived from the above, it requires substantial deviation from the Python mechanism for using the class (for example, requiring to `import qiskit.tools.layouts` as a way of modifying `Coupling`, or having an attribute added to `__init__()` unexpectedly).
* in this particular case, there are also architectural concerns: ideally, each class should be nicely encapsulated and be responsable only over its functionality, and including plotting functions into it is blurring the lines quite a bit.

With this in mind, and unless there is some extra constraint or force that might affect this particular case, I'd strongly argue in favor of not modifying classes dynamically - as you experienced (or maybe "suffered" might be a better choice of words :smile: ), we are using it for the gates definitions, but it is a mechanism that should be used with extra care and only if circumstances require it.

If that is not the case, could you implement the plotter in its own class/module, keeping `Coupling` untouched and instead providing a `tools.something.plot_coupling()` method that can be used independently? We have similar methods (the latex and png plotting functions) in `tools/visualization.py` that might serve as an example.

**Comment by afu1** [comment]
@diego-plan9 Thanks for your input.

>        dropping support for networkx 1.x:  ...
We can do this in steps and initially just go to 2.0 as a minimum?

>        tests: ...
understood but it will take a while

>         pygraphviz dependency: ...
>         Can you:
>         add some code for checking that the package is installed and failing gracefully if not?
>         add a note in the docstring of the main function to note that it requires pygraphviz
>         add an entry to the extras_require in setup.py.in

yes

>         adding methods and attributes to Coupling dynamically: 

In my mind everything directly associated with a class definition should be part of that class and plotting, saving, creating standard representations etc. is definitely something that I believe is something closely related. So I would turn your argument around and say the ultimate goal is to add this functionality to the original Class definition. This would avoid your first three issues. The reason not to suggest this from the start was a discussion with @ajavadia where I came away with the impression that it should be done in a class definition but in the tools. I feel strongly that it does not make sense to introduce another class with just the added functionality as you seem to suggest. That is against my understanding of grouping functionality in a code and it would not really be compatible with earlier code. The nice thing now is that you just add `import qiskit.tools.coupling_layouts` in whatever code you already have written and the Coupling class will continue to work the way it did but you have the extra functionality also. At least this seemed to work well when I tested it.

>         in this particular case, there are also architectural concerns: ideally, each class should be 
>         nicely encapsulated and be responsible only over its functionality, and including plotting 
>         functions into it is blurring the lines quite a bit.

I'm not sure I see this the same. The class represents coupling-maps and there should be methods to output the maps either as data, text, file or as a graphical representation. ( I guess the graphical aspect is a bit focused on the jupyter work and less applicable on the python only things - so maybe some checks should be provided to see what the environment is we're running under.
There should definitely be some functionality to create standard instances for coupling maps and I think that should go in the class definition - otherwise you could take the directed graph straight from networkx.


>         If that is not the case, could you implement the plotter in its own class/module, keeping Coupling 
>         untouched and instead providing a tools.something.plot_coupling() method that can be used 
>         independently? 

If you prefer this, then we can take the code from the challenge and just include the python file in the tools directory. I don't like that option very much though. Can you say a bit more general what plans exist to have well defined formats for generating, plotting, saving and passing (in functions) circuits and coupling maps? What information should be part of each respective data structure?

**Comment by ajavadia** [comment]
@afu1 @diego-plan9 I share diego's concern about the need for functionalities being explicit vs. implicit. Someone reading the `Coupling` class might not realize all the things that "might" be accomplished by this class if only they use a new `import` statement. 
That being said, I think it is open for interpretation whether visualization is part of the functionality of a class or it should be kept separate. For example I added code for the `circuit_drawer()` in `tools/visualization.py`, and the reason was that every other visualization was already there. But I could just as well have added it as a method of the `QuantumCircuit` class. 
But I think if it goes as part of the class, it should be static and not dynamic.

**Pull request closed without merging**
