### PR TITLE
Sphinx documentation revision

### PR DESCRIPTION
**Pull request by diego-plan9**
## Description

This PR comprises modifications to the sphinx documentation (used for generating http://www.qiskit.org/documentation/), aimed for gathering feedback and iterating further. The core of the changes are:
* **general structure**: instead of a single page, the documentation has been split in several sections. Please note the actual contents have **not** been changed - only reorganized. The purpose is to ease the exposure of the user to the SDK, trying to guide new users gently and at the same time allow expert users to jump directly to the sections that are relevant to his needs. It also allows for expanding the documentation in the future easily without requiring to change the overall structure, having a valid Table of Contents in the process.
* **index page** (ie. the [top-level page](https://diego-plan9.github.io/doc/)): in the spirit of other packages using sphinx documentation, it has been keep relatively light of content on purpose, acting as a table of contents with some quick links to the modules, following the same rationale as used for the splitting of the documentation in chapters.
* **automatic API documentation** (renamed to [SDK Reference](https://diego-plan9.github.io/doc/_autodoc_stubs/qiskit.html)): the autodocs now only include the "Public" methods (those imported from the main module), after a discussion with other members of the team based on the impression that advanced users would jump straight into the code if needed. A friendlier view that uses autosummary to display the contents of each page, and a summary of each class methods, has been included replacing the full list of raw contents.

The output of the changes on this PR can be found at https://diego-plan9.github.io/doc/ for convenience (will be updated when new commits are added to this PR).

## Motivation and Context

This PR is an attempt to make the documentation friendlier to both new SDK users and developers interested in exploring the SDK, and achieve the right balance.

Issues still to be discussed/fixed:
* personally, I feel there is a slightly bigger than expected gap between the first example (quickstart) and the information about the SDK from a developer perspective. Perhaps it would be a good idea to devote a chapter (or add some content after the first example) including more information about the usual `QuantumProgram` usage/worfklow/operations (ie. build, compile, results, etc)?
* the automatic API docs currently do not include enough information about the `simulator` package, in part due to the [auto-discovery mechanism](https://github.com/QISKit/qiskit-sdk-py/blob/master/qiskit/simulators/_localsimulator.py#L55). I still need to investigate the issue: a short-term backup solution would be to hard-code the name of the simulators.
* the style and visual aspects of the theme have not been considered a priority for this PR - however, in the future it might be beneficial to switch to a more designer-friendly Sphinx theme, as the current one might be a bit unflexible for certain types of changes.
* the generation of the automatic API docs is a bit convoluted internally (made in two passes), mostly due to the handling of private vs public members. Long-term it might be a good idea to invest some time clarifying a bit the SDK concept of public vs private.

## How Has This Been Tested?
`make doc` 

## Screenshots (if appropriate):
index
index-mobile
apidoc

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by ewinston** [comment]
I noticed that the module level documentation seemed to get cut from autoapi generated documentation. For instance the class LocalSimulator is described but not how the module works which describes how to add new backend modules. Is this information elsewhere or can we return it?

**Comment by diego-plan9** [comment]
Thanks, Erick - it is a byproduct of some of the issues mentioned on the "Motivation and context" paragraph on the PR, but I fully agree the documentation about the simulators is very relevant and something that should be addressed.

In this case, the absence of that text it is a combination of:
* all the simulators (except `LocalSimulator`) being "private" (by our current lax definition of private and current conventions). This means that they are not reachable by the `imports` chains, and the auto documentation does not pick them by default.
* more importantly, the way the simulators are "auto discovered" now. The current mechanism (`from ._localsimulator import *` on `__init__` and [the populating of `_simulator_classes`](https://github.com/QISKit/qiskit-sdk-py/blob/a2ff62bd148fb7180bf1c8ae6c2bbc3cde2256f6/qiskit/simulators/_localsimulator.py#L54-L67) makes it difficult for sphinx to automatically inspect the simulators using the standard tools, as it relies mostly on the standard `import` mechanism.

As a matter of fact, could you let me know the rationale for using the simulator auto-discovery mechanism instead of a more traditional (ie. imports and maybe subclasses) approach? It seems very useful for extending the SDK in the case there are a lot of simulators and they are constantly changing, but at the moment it seems to be adding quite a complexity to the code and friction with existing tools (sphinx, the IDEs, etc) that seems a candidate for refactoring a bit.

Shorter term, I will make some changes for including the documentation about the simulators - which probably will involve manually hard-coding the files to be included for the moment.

**Comment by ewinston** [comment]
I think the The motivation for the discovery mechanism was to allow people to easily add their own simulator backends by just dropping in the module. Previously it was necessary for the specific module to be imported into _quantumprogram and for the simulation developer to call their module by name there. By having QuantumProgram only having to "know" about LocalSimulator it doesn't have to change just because a new backend was introduced.  It should be possible, however, to let the modules themselves appear as a part of the import. I am working on an abstract base class for backends at the moment so maybe I can revisit this.

**Comment by diego-plan9** [comment]
Hmm, with the current setup, the docstrings for the _modules_ (ie. the one at the top of each `something.py` file, except for `__init__.py`) should be included in the final result - could it be a case that we actually do not have _public modules_ (and with this PR, only public entities are included)? At the moment most of the items on this PR's docs are either classes (which will only contain docstrings from inside the class) or packages (which will include docstrings from `__init__.py`), as a side effect of only documenting the "public" ones. 

With the latest couple of commits the documentation for the `simulator` _modules_ is included, though (and hence catching the missing docstrings at the top of each file!), as shown [here](https://diego-plan9.github.io/doc/_autodoc/qiskit.simulators.html#module-qiskit.simulators). This is done via manually specifying which private modules/classes are included - if there are other important ones that might be missing, could you point me to those? It's not the ideal approach, but one that would work until we revise a bit more the decision of public vs private in general.

**Comment by ewinston** [comment]
I'm not sure it makes sense to document a class inside a _private module_ but not the _private module_ itself. I think many modules include docstrings but often they repeat the docstrings of their primary class. Never the less I think we should support it. It seems like the autodoc module you're using should have an option that allows that.

Maybe we can put this off for now until we address public vs private modules.

**Comment by diego-plan9** [comment]
It is certainly a bit counter-intuitive indeed, but the reason for having a "private" class documented and not its "private" module is indeed heavy related to the way we are handling the imports (and the public vs private distinction).

Currently, we allow (and encourage in the examples and documentation) the user to import `QuantumProgram` using:
```python
from qiskit import QuantumProgram
```
due to the  `from ._quantumprogram import QuantumProgram` line   [`quiskit/__init__.py`](https://github.com/diego-plan9/qiskit-sdk-py/blob/389123df46d38546200ec95cb80e6d6aa976d67b/qiskit/__init__.py#L11). Perhaps a better word would be "exposed" classes: we are exposing to the user just the classes imported in `__init__.py`, and not the modules (`qiskit._quantumprogram`, in the example); and the autodoc on this PR is picking up only those exposed items.

On the conversations shortly before starting the PR, the general feeling was that documenting all the private classes and modules was very verbose and confusing for the expected user (and assuming the advanced users, at least at this stage, would end up inspecting the code directly), but would be happy to revisit the decision or include any specific docstrings/classes/modules that might have been overlooked (as done with the simulators package)!

> Maybe we can put this off for now until we address public vs private modules.

That is my feeling as well - I think both the discussion and the documentation details would be much more straight forward to decide once we address the public vs private issue as a whole :+1:

**Pull request merged**
