### PR TITLE
Linter fix

### PR DESCRIPTION
**Pull request by desireevl**
## Description
Reformatted a few lines and changed a few variable names to reduce errors from the linter. Not all issues have been fixed yet.

## Motivation and Context

#90 

## How Has This Been Tested?

Only minor changes were made, should not have affected anything.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by desireevl** [comment]
No worries @diego-plan9, didn't notice the lack of last lines I'll change them now :)

**Comment by diego-plan9** [comment]
Thanks again! Unfortunately some tweaks to the "newline at the end of the files" is needed to avoid introducing new linters warning - the short version is that there should be one (and only one) new line character after the last regular character at the end of the file, ie:
```
    return result\n
```

It's a bit annoying, but that should make the linter happy ... and have the PR ready to be merged!

**Comment by desireevl** [comment]
Sorry, have had a few issues with github and my editor about the newlines. Let me know if it's still not right

**Comment by diego-plan9** [comment]
Thanks again, and looking forward to more contributions! For future references, and in case it makes your workflow easier, you can use the [`.git/info/exclude` file](https://help.github.com/articles/ignoring-files/#explicit-repository-excludes) in your local repository to ignore certain files just for your local copy (such as the `.idea` folder in your case). Thanks for contributing!

**Pull request merged**
