### PR TITLE
Fix bug # 409 and duplicate #433

### LINKED ISSUE #409: A bug in circuit initialization
Providing incorrect number of arguments.
Here: https://github.com/QISKit/qiskit-sdk-py/blob/master/qiskit/extensions/quantum_initializer/_initializer.py#L103

The method `circ.initialize` only takes 2 arguments but 3 is given. (https://github.com/QISKit/qiskit-sdk-py/blob/master/qiskit/extensions/quantum_initializer/_initializer.py#L438)

## Possible Solution
change that line to `self._modifiers(circ.initialize(self.param, self.arg))`

### LINKED ISSUE #433: Circuits obtained from `initialize` cannot be combined
Circuits obtained by `initialize` cannot be combined. 

## Expected Behavior

Circuits generated by `initialize()` should behave the same with those created manually. 
Circuits constructed manually can be combined with `+` as below:
```
qp = QuantumProgram()
q = qp.create_quantum_register("q", 1)
c = qp.create_classical_register("c", 1)
qc1 = qp.create_circuit("H1", [q], [c])
qc1.h(q)

qc2 = qp.create_circuit("H2", [q], [c])
qc2.x(q)
qc2.h(q)

qp.add_circuit("H1_and_H2", qc1 + qc2) 
circuit_drawer(qp.get_circuit("H1_and_H2"))
```
This will create a concatenated circuit as in the image below:
image

## Current Behavior

The following code generates error:
```
qp = QuantumProgram()
q = qp.create_quantum_register("q", 1)
c = qp.create_classical_register("c", 1)
qc1Error = qp.create_circuit("H1", [q], [c])
qc1Error.initialize([1.0/np.sqrt(2), 1.0/np.sqrt(2)], [ q[0] ])

qc2Error = qp.create_circuit("H2", [q], [c])
qc2Error.initialize([1.0/np.sqrt(2), -1.0/np.sqrt(2)], [ q[0] ])

qp.add_circuit("H1_and_H2", qc1Error + qc2Error) 
```
Note that qc1Error and qc2Error are essentially "H" and "X H" as below: 
image
image

## Possible Solution

No Idea. Here is the error message:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-27-515dca717837> in <module>()
     10 qc2Error.initialize([1.0/np.sqrt(2), -1.0/np.sqrt(2)], [ q[0] ])
     11 
---> 12 qp.add_circuit("H1_and_H2", qc1Error + qc2Error)
     13 
     14 

~/miniconda3/envs/QISKitenv/lib/python3.6/site-packages/qiskit/_quantumcircuit.py in __add__(self, rhs)
    142     def __add__(self, rhs):
    143         """Overload + to implement self.concatenate."""
--> 144         return self.combine(rhs)
    145 
    146     def __iadd__(self, rhs):

~/miniconda3/envs/QISKitenv/lib/python3.6/site-packages/qiskit/_quantumcircuit.py in combine(self, rhs)
    114         circuit = QuantumCircuit(*combined_registers)
    115         for gate in itertools.chain(self.data, rhs.data):
--> 116             gate.reapply(circuit)
    117         return circuit
    118 

~/miniconda3/envs/QISKitenv/lib/python3.6/site-packages/qiskit/extensions/quantum_initializer/_initializer.py in reapply(self, circ)
    101     def reapply(self, circ):
    102         """Reapply this gate to the corresponding qubits in circ."""
--> 103         self._modifiers(circ.initialize(self.name, self.param, self.arg))
    104 
    105     def gates_to_uncompute(self):

TypeError: initialize() takes 3 positional arguments but 4 were given
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 3.6.1):
* Operating System and version:

### PR DESCRIPTION
**Pull request by ismaila-at-za-ibm**
## Description

 Removed self.name as first argument in function reapply (InitializeGate fixes the name to "init", is there a need to allow for an arbitrary name?).

## Motivation and Context
fixes #433 
fixes #409 

## How Has This Been Tested?
Included a new test.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed (I tested the new test, the others should pass since no other changes were made).

### CODE REVIEW

**Comment by diego-plan9** [comment]
Thanks, @ismaila-at-za-ibm ! Can you revise the new `test_combiner` check? It seems to be [passing when using the Python simulator](https://travis-ci.org/QISKit/qiskit-sdk-py/jobs/374263464#L898), but [failing when using the C++ simulator](https://travis-ci.org/QISKit/qiskit-sdk-py/jobs/374263466#L1531), with:

```
quantum_state = result.get_data("H1_and_H2")['quantum_state']

**Comment by ajavadia** [comment]
@ismaila-at-za-ibm thanks for the PR!

after #435, the correct key is now `statevector` and not `quantum_state`. 
There is also a more convenient function `result.get_statevector("H1_and_H2")`

**Comment by ajavadia** [comment]
@ismaila-at-za-ibm I made one PR into your branch to just remove any remaining use of quantum program, in line with newer qiskit conventions. After you merge that, then I think we are good to merge here.
thanks!

**Comment by diego-plan9** [comment]
Thanks @ismaila-at-za-ibm and @ajavadia !

**Pull request merged**
