### PR TITLE
Do Python version check in init

### PR DESCRIPTION
**Pull request by nonhermitian**
Check Python version in __init__ as done by NumPy and SciPy for equivalent checks.

## Description
Do Python version check at import, as opposed to a manual assert (as done in the tutorials).

## Motivation and Context
Having a manual assert in the tutorials is silly.  Checks in tutorials can be removed after commit.

## How Has This Been Tested?
I ran it.

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by ajavadia** [comment]
@nonhermitian thanks Paul. There are some linter errors, mainly having to do with putting code above the imports. Maybe it is better to put this check in `qiskit/_util.py`, since that already has a check for the API version in it. Then include a reference to it at the bottom of `__init.py__`.

**Comment by nonhermitian** [comment]
Surely you would like to do the check before doing the actual imports, A la [SciPy `__init__`](https://github.com/scipy/scipy/blob/master/scipy/__init__.py)?  Why load something if the versions are not correct.  There may be issues that raise exceptions before one even gets to the bottom of the `__init__` .

**Comment by nonhermitian** [comment]
It seems that `wrong-import-order` is already disabled for pylint.  Why not add `wrong-import-position` to the list and do the check first?

**Comment by ajavadia** [comment]
Ok, that works. The same argument can be applied to `check_ibmqe_version`, which importing `QuantumProgram` depends on.

**Comment by ajavadia** [comment]
Thanks!

**Pull request merged**
