### PR TITLE
Stable

### PR DESCRIPTION
**Pull request by juz1970**
#Author: Justin Roberts
#Date: 21 March 2018
#A simple(ish) Quantum score for examining statistical correlations between non-interacting qubits
#A strong correlation is maintained between qubit 0 and qubit 2 despite the choice of whether
#or not to apply the Pauli X to qubit 2 'after' qubit 0 is measured. qubits 3 and 4 serve no purpose in the #circuit except as an experimental control to demonstrate that the Pauli X set up is legitimate for qubit 2
#run the experiment a few times with and without the Pauli X's on qubits 2 and 3 
import matplotlib.pyplot as plt
from qiskit.tools.visualization import plot_histogram
from qiskit import QuantumProgram
import Qconfig

Q = {
	"name": "entanglement",
	"circuits": [{
	"name": "Circuit",
	"quantum_registers": [{
	    "name": "qr_1",
	    "size": 5
	}],
	"classical_registers": [{
 	   "name": "cr_1",
 	"size": 5
	}]}],
}

qp = QuantumProgram(specs=Q)
qp.set_api(Qconfig.APItoken, Qconfig.config['url'])
qc = qp.get_circuit("Circuit")
qr = qp.get_quantum_register("qr_1")
cr = qp.get_classical_register('cr_1')

qc.x(qr[0])
qc.h(qr[1])
qc.cx(qr[1],qr[0])
qc.h(qr[0])

qc.measure(qr[0],cr[0])

qc.x(qr[3])
qc.h(qr[2])
qc.h(qr[3])
qc.x(qr[2])
qc.x(qr[3])
qc.cx(qr[2],qr[1])
qc.cx (qr[3],qr[4])
qc.h(qr[1])
qc.h(qr[2])
qc.h(qr[3])

qc.measure(qr[1],cr[1])
qc.measure(qr[2],cr[2])
qc.measure(qr[3],cr[3])
qc.measure(qr[4],cr[4])

bk='local_qasm_simulator'
shots=1024
circuits = ['Circuit']
result = qp.execute(circuits, bk, shots=int(shots))
res1=result.get_counts('Circuit')
print(res1) 
plot_histogram(res1)
print(result.get_ran_qasm('Circuit'))

### CODE REVIEW

**Comment by diego-plan9** [comment]
Closing this PR as is not valid (merging from `stable` is not done via PRs, and there seems to be no other changes) - please feel free to comment back if needed.

**Comment by juz1970** [comment]
@diego-plan9. Sorry I think I messed this up. First time using Github and I obviously don't know what i'm doing. I was trying to contribute this small script for anyone who may find it useful.

**Comment by diego-plan9** [comment]
No worries, @juz1970 - it was part of a round of cleaning the repository a bit, and I could not infer your intention based on the contents of the PR :+1: 

We have some examples on how to use features or demonstrations of some concepts in the [`python/examples`](https://github.com/QISKit/qiskit-sdk-py/tree/master/examples/python) folder - could you place the script you mention in an actual file at `python/examples/the_name_of_your_example.py`, along with some descriptive comments, and issue a new PR? You can check the files in that folder for inspiration and a general look at how they are usually structured (they tend to have detailed comments on the significant parts, as they are geared towards users getting used to qiskit and demonstrate specific features).

**Comment by juz1970** [comment]
@diego-plan9 OK thanks for that, think I'm getting the hang of it now :) I notice that there are software testing jobs labelled as good for first contributions. With that in mind, I have an old 16GB  dell server that needs dusting off and firing up. I think it was designed by Charles Babbage but its still a good machine. It seems a shame not to use it. Anyway, I could use it to do some random simulator testing or something of that nature for you if you like. Regards.

**Pull request closed without merging**
